# Generated by Django 4.1.2 on 2023-01-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_userpost_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpostcomments',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
