# Generated by Django 4.1.2 on 2023-01-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_userpostcomments_no_of_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpostcomments',
            name='no_of_likes',
        ),
        migrations.AddField(
            model_name='userpost',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
