# Generated by Django 4.1.2 on 2023-01-16 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_userpostcomments_no_of_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpostcomments',
            old_name='post',
            new_name='userpost',
        ),
    ]
